# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hun-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hun-web
  template:
    metadata:
      labels:
        app: hun-web
    spec:
      containers:
      - name: web-app
        # 반드시 '본인ID/이미지이름' 형식이어야 합니다!
        image: junguihun/hun-app:latest 
        ports:
        - containerPort: 5000