# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hun-web-app-service
spec:
  selector:
    app: hun-web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP